web/src/components/System/component/MemberAdd.tsx
Fix: Handle Promise rejection in copyUserInfo
Modified the copyUserInfo function in MemberAdd.tsx to await the navigator.clipboard.writeText() Promise and handle potential rejections. This ensures that appropriate success or error messages are displayed to you. Output:
Fix: Handle Promise rejection in copyUserInfo
I've modified the copyUserInfo function in MemberAdd.tsx to await the navigator.clipboard.writeText() Promise and handle potential rejections. This ensures that appropriate success or error messages are displayed to you.
=> fix issue#35

web/app/src/components/footer/index.tsx, web/app/src/views/home/index.tsx, web/app/src/views/node/DocAnchor.tsx, web/app/src/views/node/index.tsx, web/app/src/views/node/useScroll.ts
=> fix(fe/app): footer ui

web/admin/package.json, web/admin/pnpm-lock.yaml, web/admin/src/components/Drag/DragRecommend/Item.tsx, web/admin/src/pages/release/components/VersionPublish.tsx, web/app/package.json, web/app/pnpm-lock.yaml, web/app/src/app/layout.tsx, web/app/src/components/header/index.tsx, web/app/src/theme.ts, web/app/src/views/home/index.tsx, web/app/src/views/node/Catalog.tsx, web/app/src/views/node/CatalogFolder.tsx, web/app/src/views/node/DocAnchor.tsx, web/app/src/views/node/DocHeader.tsx, web/app/src/views/node/index.tsx
feat(fe/app): 显示文档摘要
feat(fe/app): 文档详情页搜索位置放到Header中
feat(fe/admin): 发版默认全选
fix(fe): 控制台报错
feat(fe/app): ui pref
fix(fe/app): 文档页刷新大纲丢失bug
=> 修复并优化了一下功能

web/admin/src/pages/document/component/DocAddByUrl.tsx, web/admin/src/pages/document/component/EditorSummary.tsx, web/admin/vite.config.ts
=> feat(fe/admin):  RSS、Notion 导入选中再爬取页面

backend/cmd/api/wire_gen.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/wikijs.go, backend/handler/v1/crawler.go, backend/usecase/app.go, backend/usecase/provider.go, backend/usecase/wikijs.go, backend/usecase/wikijs_test.go
=> Wikijs exported file explain

web/admin/src/pages/document/component/EditorHeader.tsx, web/admin/src/pages/document/editor.tsx
fix(fe/admin): 编辑器保存导致光标移动到文末 #438
=> 修复了编辑器保存导致光标移动到文末

backend/usecase/feishu.go
=> 增加飞书文档导入调试信息

backend/handler/share/chat.go, backend/repo/ipdb/ip_addr.go
请勾选适用的变更类型:
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix: ip check

web/admin/src/components/Emoji/index.tsx
简要描述这次 PR 的目的和内容
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix(fe/admin): emoji 新增中文本地文件

web/app/src/views/widget/index.tsx
简要描述这次 PR 的目的和内容
- 修复 #123
- 关联 #456
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix(fe/app): 插件优化样式

web/admin/src/pages/setting/component/CardRobotWebComponent.tsx
简要描述这次 PR 的目的和内容
- 修复 #123
- 关联 #456
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 修改了网页挂件机器人的表单

web/admin/src/api/type.ts, web/admin/src/pages/setting/component/CardRobotApi.tsx, web/admin/src/pages/setting/component/CardRobotDing.tsx, web/admin/src/pages/setting/component/CardRobotDiscord.tsx, web/admin/src/pages/setting/component/CardRobotFeishu.tsx, web/admin/src/pages/setting/component/CardRobotWecom.tsx, web/admin/src/pages/setting/component/CardRobotWecomService.tsx
简要描述这次 PR 的目的和内容
请勾选适用的变更类型:
1. 为各种机器人增加了开关功能
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 为问答机器人增加了开关

web/admin/src/components/Header/index.tsx, web/admin/src/constant/enums.ts, web/admin/src/pages/conversation/Detail.tsx, web/admin/src/pages/conversation/index.tsx, web/admin/src/pages/document/editor.tsx
新增问答反馈功能，修复了一些问题
请勾选适用的变更类型:
1. feat(fe/app): chat feedback
2. fix(fe/admin): 修复 Issue #588
3. fix(fe/admin): 修复 Issue #561 
4. fix(fe/app): 修复了移动端插件不能移动的问题
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix(fe): 修复了一些问题

web/app/src/app/(pages)/(docs)/node/[id]/page.tsx
修复首次刷新文档页为空的问题
请勾选适用的变更类型:
1. 修复首次刷新文档页为空的问题
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 修复首次刷新文档页为空的问题

web/admin/src/components/ShowText/index.tsx, web/admin/src/pages/setting/component/CardBasicInfo.tsx, web/admin/src/pages/setting/component/CardRobotWebComponent.tsx, web/admin/src/pages/setting/component/CardWebCustomCode.tsx
网页挂件机器人嵌入代码origin未展示的问题
请勾选适用的变更类型:
1. 网页挂件机器人嵌入代码origin未展示的问题
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 网页挂件机器人嵌入代码origin未展示的问题

web/admin/package.json, web/admin/pnpm-lock.yaml, web/app/package.json, web/app/pnpm-lock.yaml
修复了编辑器复制标题导致大纲 id 一致的问题
- 修复 #598 
请勾选适用的变更类型:
3. 
描述本次变更的测试情况:
=> fix(fe): 修复了编辑器复制标题导致大纲 id 一致的问题

backend/usecase/confluence.go
=> confluence导出文档中base64图片解析修复

backend/cmd/api/wire_gen.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/comment.go, backend/handler/share/comment.go, backend/handler/v1/comment.go, backend/handler/v1/provider.go, backend/repo/pg/comment.go, backend/usecase/comment.go
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 后台实现展示用户反馈

web/app/src/views/node/DocContent.tsx
=> feat: 添加 ip 地址

backend/usecase/feishu.go
=> 修复飞书导入一些权限问题

backend/handler/share/app.go, backend/pkg/bot/wechat/wechat.go, backend/pkg/bot/wechatservice/wechat.go, backend/usecase/wechat_app.go
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 优化企业微信机器人和实现微信客服转人工

web/app/src/provider/index.tsx, web/app/src/views/home/index.tsx, web/app/src/views/node/DocContent.tsx
=> fix: 拖动目录问题

backend/go.mod, backend/usecase/confluence.go, backend/usecase/feishu.go, backend/utils/epub.go, backend/utils/utils.go
=> 优化部分代码，增加代码稳定性

web/admin/src/pages/feedback/Comments.tsx, web/admin/src/pages/feedback/Correction.tsx, web/app/src/hooks/useTextSelection.ts
=> fix: 设置默认 不开启文档纠错

web/admin/src/components/Sidebar/AuthTypeModal.tsx, web/app/src/components/markdown2/index.tsx
=> fix: md 渲染 html 问题

web/app/src/views/node/DocContent.tsx
=> fix: 更改TiptapReader 渲染

web/admin/src/pages/setting/component/CardAuth.tsx
=> style: 间距调整

backend/consts/auth.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/go.mod, backend/pkg/oauth/oauth.go
支持三方oauth接入
请勾选适用的变更类型:
1. 支持三方oauth接入
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat oauth

backend/config/config.go, backend/handler/v1/file.go, backend/repo/pg/comment.go, backend/usecase/file.go, web/admin/server.conf, web/admin/src/components/UploadFile/Drag.tsx, web/admin/src/pages/document/component/ImportDoc/Confluence.tsx, web/admin/src/pages/document/component/ImportDoc/Epub.tsx, web/admin/src/pages/document/component/ImportDoc/OfflineFile.tsx, web/admin/src/pages/document/component/ImportDoc/Wikijs.tsx, web/admin/src/pages/document/component/ImportDoc/Yuque.tsx, web/admin/src/pages/document/component/ImportDoc/index.tsx
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 修复bug和文件上传大小

web/admin/src/pages/document/component/EditorHeader.tsx, web/admin/src/pages/setting/component/CardAI.tsx, web/admin/src/pages/setting/component/CardAuth.tsx, web/admin/src/pages/setting/component/CardFeedback.tsx, web/admin/src/pages/setting/component/CardKB.tsx, web/admin/src/pages/setting/component/Common.tsx, web/admin/src/request/pro/Block.ts, web/admin/src/request/pro/index.ts, web/admin/src/request/pro/types.ts, web/admin/src/vite-env.d.ts
=> feat: 关键词屏蔽

backend/usecase/chat.go, backend/utils/DFA.go
请勾选适用的变更类型:
1. 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 优化buffsize计算

backend/usecase/yuque.go
=> fix invalid url condition

web/admin/api-templates/http-client.ejs, web/admin/src/api/type.ts, web/admin/src/pages/feedback/Correction.tsx, web/admin/src/pages/stat/Statistic/RTVisitor.tsx, web/admin/src/request/httpClient.ts, web/admin/src/request/pro/httpClient.ts, web/admin/src/request/pro/types.ts, web/admin/src/request/types.ts
=> feat: 添加用户信息

web/admin/eslint.config.js, web/admin/src/App.tsx, web/admin/src/api/index.tsx, web/admin/src/components/KB/KBCreate.tsx, web/admin/src/components/KB/KBDelete.tsx, web/admin/src/components/Sidebar/AuthTypeModal.tsx, web/admin/src/components/Sidebar/index.tsx, web/admin/src/components/System/component/MemberDelete.tsx, web/admin/src/components/System/component/MemberUpdate.tsx, web/admin/src/pages/document/component/ImportDoc/Feishu.tsx, web/admin/src/pages/document/component/ImportDoc/Notion.tsx, web/admin/src/pages/login/index.tsx, web/admin/src/pages/release/index.tsx, web/admin/src/pages/setting/component/AddRole.tsx, web/admin/src/pages/setting/component/CardKB.tsx, web/admin/src/store/slices/config.ts
- 去除部分旧接口
- 修复权限重定向路径
请勾选适用的变更类型:
=> refactor: 去除部分旧接口, 修复权限重定向路径

web/app/api-templates/http-client.ejs, web/app/src/middleware.ts, web/app/src/request/httpClient.ts, web/app/src/request/pro/httpClient.ts, web/app/src/utils/getServerHeader.ts, web/app/src/utils/index.ts, web/app/src/views/auth/login.tsx
=> feat: 添加 redirect url

sdk/rag/document.go
=> fix: 区分[]和nil

web/admin/package.json, web/admin/pnpm-lock.yaml, web/app/package.json, web/app/pnpm-lock.yaml
feat(fe): 拖拽按钮支持点击块级操作
请勾选适用的变更类型:
描述本次变更的测试情况:
任何其他需要说明的事项:
=> 拖拽按钮支持点击块级操作

web/admin/src/pages/document/component/DocPropertiesModal.tsx, web/admin/src/pages/setting/component/CardAuth.tsx
=> feat: 修改用户组为联创版和企业版可用

web/app/src/components/watermark/WaterMarkProvider.tsx
=> fix: username undefined

web/admin/src/components/System/component/MemberAdd.tsx, web/admin/src/pages/setting/component/CardKB.tsx, web/admin/src/store/slices/config.ts
新增管理员可以添加 wiki 站管理员
请勾选适用的变更类型:
=> feat: 新增管理员可以添加 wiki 站管理员

backend/api/stat/v1/stat.go, backend/cmd/api/wire_gen.go, backend/cmd/consumer/wire_gen.go, backend/consts/consts.go, backend/consts/license.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/json.go, backend/domain/stat.go, backend/handler/mq/provider.go, backend/handler/mq/stat.go, backend/handler/v1/stat.go, backend/repo/cache/geo.go, backend/repo/pg/conversation.go, backend/repo/pg/knowledge_base.go, backend/repo/pg/stat.go, backend/repo/pg/stat_hour.go, backend/store/pg/migration/000023_create_stat_page_hours.down.sql, backend/store/pg/migration/000023_create_stat_page_hours.up.sql, backend/usecase/stat.go, backend/utils/time.go
支持统计 7、30、90天的维度
请勾选适用的变更类型:
1. 支持统计 7、30、90天的维度
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat stats

backend/go.mod, backend/go.sum, web/admin/package.json, web/admin/pnpm-lock.yaml
请勾选适用的变更类型:
1. 添加模型，输入api 地址使用localhost, 显示信息建议用户使用宿主机主机名
2. 添加模型，输入api 地址没有带/v1，显示信息建议用户添加/v1
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat: 添加用户添加模型出现错误时的提示信息

backend/domain/node.go, backend/repo/pg/node.go, backend/usecase/node.go
移动node相关的权限校验
请勾选适用的变更类型:
1. 移动node相关的权限校验
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix node move kbid

web/admin/src/components/System/component/Member.tsx, web/admin/src/components/System/component/MemberAdd.tsx, web/admin/src/pages/setting/component/CardAuth.tsx
=> feat: 限制管理员数量

web/admin/src/pages/stat/Statistic/HotDocs.tsx
=> fix: 修复列表问题

web/admin/package.json, web/admin/pnpm-lock.yaml
=> fix: icon 图标问题

backend/cmd/api/wire_gen.go, backend/consts/auth.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/app.go, backend/domain/auth.go, backend/handler/share/chat.go, backend/repo/pg/auth.go, backend/usecase/app.go, backend/usecase/auth.go, backend/usecase/provider.go, backend/usecase/wechat_app.go, backend/usecase/wechat_service.go
机器人支持权限配置
请勾选适用的变更类型:
- [] 新功能 (不兼容变更的新功能)
1. 机器人支持权限配置
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat support for widget auth perm

web/app/new-types.d.ts, web/app/src/app/(pages)/(doc)/node/layout.tsx, web/app/src/theme.ts, web/app/src/utils/useScroll.ts, web/app/src/views/chat/index.tsx, web/app/src/views/node/DocAnchor.tsx, web/app/src/views/node/DocContent.tsx
=> fix: 锚点失效问题

backend/api/node/v1/node.go, backend/cmd/api/wire_gen.go, backend/cmd/migrate/wire_gen.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/migration/fns/0002_create_bot_auth.go, backend/migration/fns/provider.go, backend/migration/func.go, backend/repo/pg/auth.go, backend/repo/pg/node.go, backend/usecase/app.go, backend/usecase/chat.go, backend/usecase/node.go
修复网页挂件机器人权限问题
请勾选适用的变更类型:
1. 修复网页挂件机器人权限问题
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix widget chat auth

web/admin/src/pages/document/component/DocPropertiesModal.tsx
=> fix: 用户组错误

web/admin/src/pages/setting/component/CardSecurity.tsx
=> feat: 人机验证权限

backend/domain/auth.go, backend/handler/v1/knowledge_base.go, backend/repo/pg/auth.go, backend/store/pg/migration/000024_add_parent_id_to_auth_groups.down.sql, backend/store/pg/migration/000024_add_parent_id_to_auth_groups.up.sql, backend/usecase/chat.go, backend/usecase/node.go
用户组多级分组
请勾选适用的变更类型:
1. 用户组多级分组 
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat auth group parent

sdk/rag/models.go, sdk/rag/retrieval.go
retrival接口增加chat_messages字段用来支持问题重写
=> feat: 支持问题重写

sdk/rag/retrieval.go
=> fix: 修改检索返回值

backend/cmd/api/wire_gen.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/api_token.go, backend/domain/app.go, backend/handler/v1/app.go, backend/middleware/api_token.go, backend/middleware/auth.go, backend/middleware/jwt.go, backend/repo/pg/ap_token.go, backend/repo/pg/app.go, backend/repo/pg/provider.go, backend/store/pg/migration/000025_create_api_tokens_table.down.sql, backend/store/pg/migration/000025_create_api_tokens_table.up.sql, backend/usecase/app.go
支持api-token
请勾选适用的变更类型:
1. 支持api-token
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat api token

web/admin/src/pages/setting/component/CardRobot.tsx, web/admin/src/pages/setting/component/CardRobotApi.tsx, web/admin/src/request/pro/types.ts, web/admin/src/request/types.ts
=> feat: 添加问答机器人

web/admin/src/pages/setting/component/CardRobotApi.tsx
=> fix: ts error

web/admin/src/pages/setting/component/CardRobotApi.tsx
=> fix: 修改 api token , 保存按钮出现

.github/workflows/web.yml, web/app/.gitignore, web/app/Dockerfile, web/app/Makefile, web/app/next.config.ts, web/app/package.json, web/app/sentry.edge.config.ts, web/app/sentry.server.config.ts, web/app/src/app/api/sentry-example-api/route.ts, web/app/src/app/global-error.tsx, web/app/src/app/sentry-example-page/page.tsx, web/app/src/instrumentation-client.ts, web/app/src/instrumentation.ts, web/pnpm-lock.yaml
需要添加secrets.SENTRY_AUTH_TOKEN，请联系我获取
请勾选适用的变更类型:
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat: 前端集成sentry

backend/config/config.go, backend/go.mod, backend/go.sum, backend/handler/share/captcha.go, backend/middleware/share_auth.go, backend/server/http/http.go
需在环境变量中添加SENTRY_ENABLED=true 与 SENTRY_DSN,请联系我获取
请勾选适用的变更类型:
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat: 后端集成sentry

web/app/src/app/(pages)/(doc)/(home)/layout.tsx, web/app/src/components/footer/index.tsx, web/app/src/components/header/index.tsx
欢迎页footer header组件间距调整
请勾选适用的变更类型:
1.  优化欢迎页header footer的表现
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat: 欢迎页采用全屏布局

web/admin/src/components/CustomModal/components/components/Footer.tsx, web/admin/src/components/System/component/Member.tsx, web/app/src/app/(pages)/(doc)/(home)/layout.tsx, web/app/src/components/footer/index.tsx
=> fix: brand_groups 缺失问题

web/app/src/components/footer/index.tsx, web/app/src/components/header/index.tsx
调整前台header footer间距逻辑
请勾选适用的变更类型:
1. 调整header footer间距逻辑 常驻左右40px
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat: 调整前台header footer间距逻辑

backend/api/auth/v1/auth.go, backend/api/openapi/v1/openapi.go, backend/api/share/v1/auth.go, backend/cmd/api/wire_gen.go, backend/cmd/consumer/wire_gen.go, backend/cmd/migrate/wire_gen.go, backend/consts/license.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/auth.go, backend/handler/share/auth.go, backend/handler/share/openapi.go, backend/handler/share/provider.go, backend/handler/v1/auth.go, backend/handler/v1/provider.go, backend/pkg/oauth/github.go, backend/pkg/oauth/oauth.go, backend/repo/pg/auth.go, backend/usecase/auth.go, backend/usecase/auth_github.go
github auth登录
请勾选适用的变更类型:
1. github auth登录
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat github auth

backend/consts/contribute.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/app.go, backend/domain/contribute.go, backend/store/pg/migration/000027_create_contributes_table.down.sql, backend/store/pg/migration/000027_create_contributes_table.up.sql, backend/usecase/app.go
支持前台贡献 后台审核
请勾选适用的变更类型:
1. 支持前台贡献 后台审核
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> feat contribute

web/admin/package.json, web/admin/src/pages/document/editor/edit/Wrap.tsx, web/admin/src/pages/document/editor/index.tsx, web/app/package.json, web/pnpm-lock.yaml
feat(editor): 新增功能 -- slash 插入按钮
feat(editor): 新增功能 -- 缩进功能 #751
feat(fe/admin): 新增功能 -- 编辑页切换文档触发自动保存
fix(fe/admin): 修复 -- 编辑页小概率出现加载时报错的问题
=> 编辑器功能优化 & 后台编辑页问题修复

backend/repo/pg/auth.go
对话用户信息展示
请勾选适用的变更类型:
1. 对话用户信息展示
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix conversation

backend/api/user/v1/user.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/domain/api_token.go, backend/handler/v1/kb_user.go, backend/handler/v1/knowledge_base.go, backend/handler/v1/node.go, backend/handler/v1/user.go, backend/middleware/jwt.go, backend/repo/pg/knowledge_base.go, backend/usecase/knowledge_base.go
fix kb list token
请勾选适用的变更类型:
1. fix kb list token
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix kb list token

backend/api/crawler/v1/confluence.go, backend/api/crawler/v1/crawler.go, backend/api/crawler/v1/feishu.go, backend/api/crawler/v1/notion.go, backend/docs/docs.go, backend/docs/swagger.json, backend/docs/swagger.yaml, backend/handler/v1/crawler.go, backend/pkg/anydoc/anydoc.go, backend/pkg/anydoc/confluence.go, backend/pkg/anydoc/epub.go, backend/pkg/anydoc/feishu.go, backend/pkg/anydoc/notion.go, backend/pkg/anydoc/rss.go, backend/pkg/anydoc/sitemap.go, backend/pkg/anydoc/wikijs.go, backend/pkg/anydoc/yuque.go, backend/usecase/crawler.go, backend/usecase/crawler_feishu.go
fix anydoc uploader path
请勾选适用的变更类型:
1. fix anydoc uploader path
2. 
3. 
描述本次变更的测试情况:
任何其他需要说明的事项:
=> fix anydoc uploader path
